### ISSUE TITLE
waitForDatabase does not work if no port is specified

### ISSUE THREAD

**Issue by middagj** [ICTU/sonar#11]
The recent update to 7.9.1 broke our sonar. The reason was that our `SONARQUBE_JDBC_URL` did not specified a port and the script could not determine if the database was up. As specified in [PostgreSQL JDBC Driver](https://jdbc.postgresql.org/documentation/80/connect.html) a port is not needed in the URL.

Easy workaround is of course to specify a port. But I think it would be better to have a solution that works without a port.

**Comment by bousch** [comment]
I will look into it but am not sure if we will fix it because, even though we only use postgresql with the sonar instances we support at ICTU, sonar does support other databases.

**Comment by middagj** [comment]
As far as I know all database drivers have the port optional. See Example 3.1 at [MySQL J Connector](https://dev.mysql.com/doc/connectors/en/connector-j-usagenotes-connect-drivermanager.html)

Oracle JDBC url looks completely different but also has port optional.

**Comment by bousch** [comment]
Sure, but we will not support that.
