### ISSUE TITLE
Make the admin password configurable

### ISSUE THREAD

**Issue by enrico2828** [ICTU/sonar#13]
It seems the project assumes that the SonarQuebe password is always 'admin', e.g. in script start-with-profile.sh.

It would be nice to have the admin password as an parameter that we can set for when sonarqube is run in less trustworthy environment and needs the admin password to be secure.

**Comment by bousch** [comment]
Fixed by pull request #12

**Comment by enrico2828** [comment]
Hello @bousch Would you mind explaining how pull request #12 solves this issues? I see that the credentials to access sonarqube are still hard coded to 'admin:admin'. Do I overlook something? Thank you very much!

**Comment by bousch** [comment]
It doesn't. :)

**Comment by enrico2828** [comment]
:) Thanks for reopening :)

**Comment by bousch** [comment]
Fixed by pull request #22
