### ISSUE TITLE
SonarQube update 10.3

### ISSUE THREAD

**Issue by bousch** [ICTU/sonar#55]
Updaten naar SonarQube 10.3.X
updaten van plugins in plugins/plugin-list naar laatste versies
indien nodig updaten van profile versie nummers in start-with-profile.sh

**Comment by denniebouman** [comment]
Let op! Eerst moet de impact nog bepaald worden van de "Clean Code" wijzigingen door SonarQube en de (eventuele) impact hiervan op Quality-Time.

**Comment by bousch** [comment]
Is dit een nieuwe feature in 10.2? We gebruiken momenteel al 10.1.
