### ISSUE TITLE
Add automated functional checks

### ISSUE THREAD

**Issue by denniebouman** [ICTU/sonar#59]
- [x] configured quality profile is activated and the default
- [x] configured enabled and disabled rules are indeed enabled or disabled in the running instance
- [x] configured rule parameter values are indeed configured in the running instance
- [x] configured enabled and disabled rules by group (types) are indeed enabled or disabled in the running instance
- [ ] #71

**Comment by wkoot** [comment]
We should at least scan one repository, perhaps quality-time?
