### ISSUE TITLE
Update to SonarQube 10.5.1

### ISSUE THREAD

**Issue by javanegmond** [ICTU/sonar#76]
SonarQube 10.5 is the latest LTS-release of SonarQube. Among the important changes is proper support for new language versions, like Java 21. It would be great to get the ICTU version of the SonarQube image available as soon as possible.

https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-5/

**Comment by GNutma** [comment]
I would also like to see an update to the latest version. Mainly for the latest authenticating with GitLab features, where you can select which GitLab groups have access to the SonarQube instance. With version 10.3 you allow all GitLab users to the SonarQube instance which you need to limit access to. 

See [Provision And Sync Users And Groups From GitLab](https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-4/#provision-and-sync-users-and-groups-from-gitlab)

**Comment by denniebouman** [comment]
There seems to be a bug in v10.5 regarding GitLab authentication. We should change this to 10.5.1 @wkoot 
https://community.sonarsource.com/t/sonarqube-10-5-1-released/114587
