### ISSUE TITLE
Upgrade to SonarQube 10.7

### ISSUE THREAD

**Issue by denniebouman** [ICTU/sonar#80]
https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/release-upgrade-notes/

**Comment by wkoot** [comment]
I see a lot of errors relating to https://community.sonarsource.com/t/rules-not-registered-and-index-correctly-after-upgrade-to-10-7/128030
Need to investigate further and fix, as the `/coding_rules` indeed reports an empty list while `/profiles` reports active rules.
